[rhpam-3273] Fix example for LOG_LEVEL in SmartRouter image
jboss-container-images/rhpam-7-openshift-image pull request #477
Opened 2020-10-23 10:07 UTC by desmax74

https://issues.redhat.com/browse/RHPAM-3273

@jakubschwan

2020-10-27 16:41 UTC, spolti requested changes

2020-10-27 16:41 UTC, spolti commented on smartrouter/image.yaml
> +      example: "INFO"
Maybe use some value different than the default?

2020-11-04 15:34 UTC, spolti commented
@Kaitou786 @jakubschwan do you mind to take a look?

2020-11-04 15:34 UTC, spolti approved these changes

2020-11-04 15:36 UTC, Kaitou786 approved these changes

2020-11-05 12:45 UTC, jakubschwan approved these changes

2020-11-05 14:35 UTC, spolti commented
please cherry pick it for 7.9.x branch.

2020-11-09 17:36 UTC, spolti approved these changes

2020-11-09 17:37 UTC, merged