[KIECLOUD-466] - Avail the possibility to use the ubi8-mininal as bas…
jboss-container-images/rhpam-7-openshift-image pull request #493
Opened 2020-11-25 15:07 UTC by Kaitou786

…e image for RHPAM and RHDM images

See: https://issues.redhat.com/browse/KIECLOUD-466

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2020-11-25 16:07 UTC, msmagnanijr submitted a review, later dismissed

2020-11-26 19:59 UTC, spolti requested changes

2020-11-26 19:59 UTC, spolti commented on businesscentral-monitoring/image.yaml
>            - hostname
remove the hostname package from the image.yaml as it is being installed by the common.dependencies module.

2020-11-26 19:59 UTC, spolti commented on businesscentral/image.yaml
>            - hostname
same here.

2020-11-26 19:59 UTC, spolti commented on controller/image.yaml
>            - hostname
same here.

2020-11-26 19:59 UTC, spolti commented on kieserver/image.yaml
>            - hostname
same here.

2020-11-26 19:59 UTC, spolti commented on smartrouter/image.yaml
>            - hostname
same here.

2020-11-27 16:44 UTC, spolti approved these changes

2020-11-27 16:44 UTC, merged