[RHPAM-3283] - Align the RHPAM and RHDM modules with JBoss EAP module…
jboss-container-images/rhpam-7-openshift-image pull request #497
Opened 2020-11-30 14:34 UTC by Kaitou786

…s 7.3.x branch

See: https://issues.redhat.com/browse/RHPAM-3283

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2020-12-03 06:44 UTC, Kaitou786 commented
Depends on https://github.com/jboss-container-images/jboss-kie-modules/pull/418

2020-12-08 18:39 UTC, msmagnanijr submitted a review, later dismissed

2020-12-08 18:49 UTC, spolti requested changes
nice work, just a few comments.

2020-12-08 18:49 UTC, spolti commented on businesscentral-monitoring/image.yaml
>            - name: os-eap-launch
version is missing.

2020-12-08 18:49 UTC, spolti commented on businesscentral-monitoring/image.yaml
>            - name: os-eap7-launch
version is missing.

2020-12-08 18:49 UTC, spolti commented on controller/image.yaml
> -          - name: os-eap-launch
why removing?
version is missing as well.

2020-12-08 18:49 UTC, spolti commented on controller/image.yaml
>            - name: os-eap7-launch
version is missing.

2020-12-08 18:49 UTC, spolti commented on kieserver/image.yaml
>            - name: os-eap-launch
version is missing.

2020-12-08 18:49 UTC, spolti commented on kieserver/image.yaml
>            - name: os-eap7-launch
version is missing.

2020-12-08 19:37 UTC, spolti approved these changes
Awesome, Thanks :)

2020-12-08 19:50 UTC, merged