[RHPAM-3640] Configure Kafka JBPM Emitter from Operator
jboss-container-images/rhpam-7-openshift-image pull request #550
Opened 2021-06-29 09:38 UTC by desmax74

Thanks for submitting your Pull Request!
See: https://issues.redhat.com/browse/RHPAM-3640

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2021-06-29 09:38 UTC, desmax74 commented
@spolti

2021-06-29 23:40 UTC, spolti commented on kieserver/image.yaml
> +    description: "A comma separated list of host/port pairs to use for establishing the initial connection to the Kafka cluster, this environment variable will be used to set the org.kie.jbpm.event.e
```suggestion
    description: "Comma separated list of host/port pairs to use for establishing the initial connection to the Kafka cluster, this environment variable will be used to set the org.kie.jbpm.event.emitters.kafka.bootstrap.servers system property."
```

2021-06-29 23:41 UTC, spolti commented on kieserver/image.yaml
> +    description: "If true enable the deployment and the configuration of the emitter jar"
```suggestion
    description: "If true, will configure the JBpm Kafka events integration, when true the kafka bootstrap servers must be set."
```

2021-06-30 01:36 UTC, spolti requested changes

2021-06-30 01:36 UTC, spolti commented on kieserver/image.yaml
> +    description: "The number of acknowledgments that the emitter requires the leader to have received before considering a request to be complete."
also on the other envs you mentioned what system property it does set, maybe it worth to add here as well?

2021-06-30 01:36 UTC, spolti commented on kieserver/image.yaml
> +    description: "Value in milliseconds that indicates how long the 'publish' method will block the operation. Default 2000 milliseconds (2 seconds), this environment variable will be used to set the
wouldn't be better replace operation by thread?

2021-06-30 01:36 UTC, spolti commented on kieserver/image.yaml
> +    description: "Value in milliseconds that indicates how long the 'publish' method will block the operation. Default 2000 milliseconds (2 seconds), this environment variable will be used to set the
```suggestion
    description: "Value in milliseconds that indicates how long the 'publish' method will block the operation. Default 2000 milliseconds (2 seconds), this environment variable will be used to set the 'org.kie.jbpm.event.emitters.kafka.max.block.ms' system property."
```

2021-06-30 01:36 UTC, spolti commented on kieserver/image.yaml
> +    description: "Date and time format to be sent to Kafka, this environment variable will be used to set the org.kie.jbpm.event.emitters.kafka.date_format system property."
please mention what is the default value.

2021-06-30 01:36 UTC, spolti commented on kieserver/image.yaml
> +    description: "Date and time format to be sent to Kafka, this environment variable will be used to set the org.kie.jbpm.event.emitters.kafka.date_format system property."
```suggestion
    description: "Date and time format to be sent to Kafka, this environment variable will be used to set the 'org.kie.jbpm.event.emitters.kafka.date_format' system property."
```

2021-06-30 07:35 UTC, desmax74 commented on kieserver/image.yaml
> +    description: "The number of acknowledgments that the emitter requires the leader to have received before considering a request to be complete."
If not set is not passed to kafka, ok to specify sys prop

2021-06-30 17:50 UTC, spolti approved these changes

2021-07-01 13:48 UTC, spolti submitted a review, later dismissed

2021-07-01 13:59 UTC, jakubschwan approved these changes

2021-07-01 14:25 UTC, spolti approved these changes

2021-07-01 16:48 UTC, merged