[KIECLOUD-505] 7.12.x Update https.sh script to use the one provided by wildfly-cekit-modules
jboss-container-images/rhpam-7-openshift-image pull request #577
Opened 2021-11-29 21:20 UTC by desmax74

Signed-off-by: desmax74 <mdessi@redhat.com>
(cherry picked from commit ee73bec905233e292b2c102402b2fe4a77dae262)
See:https://issues.redhat.com/browse/KIECLOUD-505

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2021-11-30 18:42 UTC, spolti commented on businesscentral-monitoring/image.yaml
> +    - name: jboss.container.wildfly.launch.access-log-valve
same here

2021-11-30 18:42 UTC, spolti requested changes

2021-11-30 18:42 UTC, spolti commented on businesscentral-monitoring/image.yaml
> +    - name: jboss.container.wildfly.launch.access-log-valve
same here

2021-12-02 15:33 UTC, desmax74 commented on businesscentral-monitoring/image.yaml
> +    - name: jboss.container.wildfly.launch.access-log-valve
Fixed

2021-12-02 19:13 UTC, spolti submitted a review, later dismissed

2021-12-13 05:28 UTC, amadhusu approved these changes

2022-01-26 18:17 UTC, spolti commented
@desmax74 can you please rebase?

2022-01-27 13:46 UTC, spolti approved these changes

2022-01-27 13:46 UTC, merged